// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalApi.Contexts;

namespace PortalApi.Migrations
{
    [DbContext(typeof(PortalContext))]
    partial class PortalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PortalApi.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleSubcategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(2500)")
                        .HasMaxLength(2500);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ArticleSubcategoryId");

                    b.HasIndex("PersonId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleSubcategoryId = 1,
                            Content = "Rozmowy1_Content",
                            Date = new DateTime(2020, 6, 4, 21, 12, 39, 319, DateTimeKind.Local).AddTicks(991),
                            ImgSrc = "sciezka IMG 1",
                            PersonId = 1,
                            Title = "Rozmowy1-Title"
                        },
                        new
                        {
                            Id = 2,
                            ArticleSubcategoryId = 1,
                            Content = "Rozmowy2_Content",
                            Date = new DateTime(2020, 6, 5, 21, 12, 39, 321, DateTimeKind.Local).AddTicks(7443),
                            ImgSrc = "sciezka IMG 2",
                            PersonId = 1,
                            Title = "Rozmowy2-Title"
                        },
                        new
                        {
                            Id = 3,
                            ArticleSubcategoryId = 1,
                            Content = "Rozmowy3e_Content",
                            Date = new DateTime(2020, 6, 6, 21, 12, 39, 321, DateTimeKind.Local).AddTicks(7492),
                            ImgSrc = "sciezka IMG 3",
                            PersonId = 1,
                            Title = "Rozmowy3e-Title"
                        },
                        new
                        {
                            Id = 4,
                            ArticleSubcategoryId = 1,
                            Content = "Rozmowy4_Content",
                            Date = new DateTime(2020, 6, 7, 21, 12, 39, 321, DateTimeKind.Local).AddTicks(7498),
                            ImgSrc = "sciezka IMG 4",
                            PersonId = 1,
                            Title = "Rozmowy4-Title"
                        },
                        new
                        {
                            Id = 5,
                            ArticleSubcategoryId = 1,
                            Content = "Rozmowy5_Content",
                            Date = new DateTime(2020, 6, 8, 21, 12, 39, 321, DateTimeKind.Local).AddTicks(7581),
                            ImgSrc = "sciezka IMG 5",
                            PersonId = 1,
                            Title = "Rozmowy5-Title"
                        },
                        new
                        {
                            Id = 6,
                            ArticleSubcategoryId = 2,
                            Content = "Wydarzenia1_Content",
                            Date = new DateTime(2020, 6, 3, 21, 12, 39, 321, DateTimeKind.Local).AddTicks(7586),
                            ImgSrc = "sciezka IMG 1",
                            PersonId = 2,
                            Title = "Wydarzenia1-Title"
                        },
                        new
                        {
                            Id = 7,
                            ArticleSubcategoryId = 2,
                            Content = "Wydarzenia2_Content",
                            Date = new DateTime(2020, 6, 3, 21, 12, 39, 321, DateTimeKind.Local).AddTicks(7590),
                            ImgSrc = "sciezka IMG 2",
                            PersonId = 2,
                            Title = "Wydarzenia2-Title"
                        },
                        new
                        {
                            Id = 8,
                            ArticleSubcategoryId = 2,
                            Content = "Wydarzenia3_Content",
                            Date = new DateTime(2020, 6, 3, 21, 12, 39, 321, DateTimeKind.Local).AddTicks(7594),
                            ImgSrc = "sciezka IMG 3",
                            PersonId = 2,
                            Title = "Wydarzenia3-Title"
                        },
                        new
                        {
                            Id = 9,
                            ArticleSubcategoryId = 2,
                            Content = "Wydarzenia4_Content",
                            Date = new DateTime(2020, 6, 3, 21, 12, 39, 321, DateTimeKind.Local).AddTicks(7598),
                            ImgSrc = "sciezka IMG 4",
                            PersonId = 2,
                            Title = "Wydarzenia4-Title"
                        },
                        new
                        {
                            Id = 10,
                            ArticleSubcategoryId = 2,
                            Content = "Wydarzenia5_Content",
                            Date = new DateTime(2020, 6, 3, 21, 12, 39, 321, DateTimeKind.Local).AddTicks(7602),
                            ImgSrc = "sciezka IMG 5",
                            PersonId = 2,
                            Title = "Wydarzenia5-Title"
                        });
                });

            modelBuilder.Entity("PortalApi.Entities.ArticleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ArticleCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tatuaż"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Piercing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Modeling"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fotografia"
                        });
                });

            modelBuilder.Entity("PortalApi.Entities.ArticleSubcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ArticleCategoryId");

                    b.ToTable("ArticleSubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleCategoryId = 1,
                            Name = "Rozmowy"
                        },
                        new
                        {
                            Id = 2,
                            ArticleCategoryId = 1,
                            Name = "Wydarzenia"
                        },
                        new
                        {
                            Id = 3,
                            ArticleCategoryId = 1,
                            Name = "Porady o tatuażu"
                        },
                        new
                        {
                            Id = 4,
                            ArticleCategoryId = 1,
                            Name = "Relacje"
                        },
                        new
                        {
                            Id = 5,
                            ArticleCategoryId = 1,
                            Name = "Różne"
                        },
                        new
                        {
                            Id = 6,
                            ArticleCategoryId = 1,
                            Name = "Ze świata"
                        },
                        new
                        {
                            Id = 7,
                            ArticleCategoryId = 1,
                            Name = "Oferty pracy"
                        },
                        new
                        {
                            Id = 8,
                            ArticleCategoryId = 2,
                            Name = "O przekłuciu"
                        },
                        new
                        {
                            Id = 9,
                            ArticleCategoryId = 2,
                            Name = "Porady"
                        },
                        new
                        {
                            Id = 10,
                            ArticleCategoryId = 2,
                            Name = "Rozmowy"
                        },
                        new
                        {
                            Id = 11,
                            ArticleCategoryId = 2,
                            Name = "Różne"
                        },
                        new
                        {
                            Id = 12,
                            ArticleCategoryId = 3,
                            Name = "Rozmowy"
                        },
                        new
                        {
                            Id = 13,
                            ArticleCategoryId = 3,
                            Name = "Różne"
                        },
                        new
                        {
                            Id = 14,
                            ArticleCategoryId = 4,
                            Name = "Rozmowy"
                        },
                        new
                        {
                            Id = 15,
                            ArticleCategoryId = 4,
                            Name = "Różne"
                        });
                });

            modelBuilder.Entity("PortalApi.Entities.AvailableDesign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<bool>("Reserved")
                        .HasColumnType("bit");

                    b.Property<int>("Style")
                        .HasColumnType("int");

                    b.Property<int>("Technique")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("AvailableDesigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Warszawa",
                            Color = 1,
                            Date = new DateTime(2020, 6, 4, 21, 12, 39, 324, DateTimeKind.Local).AddTicks(1910),
                            Gender = 1,
                            ImgSrc = "sciezka Available Design 1",
                            PersonId = 1,
                            Reserved = false,
                            Style = 1,
                            Technique = 2
                        },
                        new
                        {
                            Id = 2,
                            City = "Poznan",
                            Color = 1,
                            Date = new DateTime(2020, 6, 5, 21, 12, 39, 324, DateTimeKind.Local).AddTicks(3022),
                            Gender = 2,
                            ImgSrc = "sciezka Available Design 2",
                            PersonId = 2,
                            Price = 300.0,
                            Reserved = true,
                            Style = 2,
                            Technique = 1
                        },
                        new
                        {
                            Id = 3,
                            City = "Krakow",
                            Color = 1,
                            Date = new DateTime(2020, 6, 6, 21, 12, 39, 324, DateTimeKind.Local).AddTicks(3053),
                            Gender = 2,
                            ImgSrc = "sciezka Available Design 3",
                            PersonId = 3,
                            Price = 199.99000000000001,
                            Reserved = false,
                            Style = 3,
                            Technique = 2
                        });
                });

            modelBuilder.Entity("PortalApi.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Warszawa"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Krakow"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Wroclaw"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            Name = "Monachium"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "Frankfurt"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 3,
                            Name = "Paryż"
                        });
                });

            modelBuilder.Entity("PortalApi.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Polska"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Niemcy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Francja"
                        });
                });

            modelBuilder.Entity("PortalApi.Entities.ModelPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<bool>("Puncture")
                        .HasColumnType("bit");

                    b.Property<bool>("Tattoo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("ModelsPhotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Krakow",
                            Date = new DateTime(2020, 7, 6, 21, 12, 39, 323, DateTimeKind.Local).AddTicks(1980),
                            Gender = 2,
                            ImgSrc = "sciezka MODEL 1",
                            PersonId = 1,
                            Puncture = true,
                            Tattoo = false
                        },
                        new
                        {
                            Id = 2,
                            City = "Warszawa",
                            Date = new DateTime(2020, 7, 7, 21, 12, 39, 323, DateTimeKind.Local).AddTicks(2536),
                            Gender = 1,
                            ImgSrc = "sciezka MODEL 2",
                            PersonId = 2,
                            Puncture = true,
                            Tattoo = true
                        },
                        new
                        {
                            Id = 3,
                            City = "Poznan",
                            Date = new DateTime(2020, 7, 7, 21, 12, 39, 323, DateTimeKind.Local).AddTicks(2560),
                            Gender = 2,
                            ImgSrc = "sciezka MODEL 3",
                            PersonId = 3,
                            Puncture = false,
                            Tattoo = false
                        });
                });

            modelBuilder.Entity("PortalApi.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("PortalApi.Entities.PhotographerPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PhotographersPhotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Krakow",
                            Date = new DateTime(2020, 6, 14, 21, 12, 39, 323, DateTimeKind.Local).AddTicks(5867),
                            Experience = 3,
                            Gender = 2,
                            ImgSrc = "sciezka Photographer 1",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            City = "Warszawa",
                            Date = new DateTime(2020, 6, 25, 21, 12, 39, 323, DateTimeKind.Local).AddTicks(6430),
                            Experience = 1,
                            Gender = 1,
                            ImgSrc = "sciezka Photographer 2",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 3,
                            City = "Poznan",
                            Date = new DateTime(2020, 7, 6, 21, 12, 39, 323, DateTimeKind.Local).AddTicks(6452),
                            Experience = 2,
                            Gender = 2,
                            ImgSrc = "sciezka Photographer 3",
                            PersonId = 3
                        });
                });

            modelBuilder.Entity("PortalApi.Entities.Piercing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Puncture")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Piercings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Krakow",
                            Date = new DateTime(2020, 6, 4, 21, 12, 39, 322, DateTimeKind.Local).AddTicks(6629),
                            Gender = 2,
                            ImgSrc = "sciezka PIERCING 1",
                            PersonId = 1,
                            Puncture = 1
                        },
                        new
                        {
                            Id = 2,
                            City = "Wroclaw",
                            Date = new DateTime(2020, 6, 5, 21, 12, 39, 322, DateTimeKind.Local).AddTicks(7205),
                            Gender = 1,
                            ImgSrc = "sciezka PIERCING 2",
                            PersonId = 1,
                            Puncture = 2
                        },
                        new
                        {
                            Id = 3,
                            City = "Poznan",
                            Date = new DateTime(2020, 6, 6, 21, 12, 39, 322, DateTimeKind.Local).AddTicks(7246),
                            Gender = 1,
                            ImgSrc = "sciezka PIERCING 3",
                            PersonId = 2,
                            Puncture = 3
                        });
                });

            modelBuilder.Entity("PortalApi.Entities.Tattoo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Style")
                        .HasColumnType("int");

                    b.Property<int>("Technique")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Tattoos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Rzeszow",
                            Color = 2,
                            Date = new DateTime(2020, 6, 15, 21, 12, 39, 322, DateTimeKind.Local).AddTicks(2186),
                            Gender = 2,
                            ImgSrc = "sciezka TATTOO 1",
                            PersonId = 1,
                            Style = 1,
                            Technique = 2
                        },
                        new
                        {
                            Id = 2,
                            City = "Warszawa",
                            Color = 2,
                            Date = new DateTime(2020, 6, 16, 21, 12, 39, 322, DateTimeKind.Local).AddTicks(3218),
                            Gender = 1,
                            ImgSrc = "sciezka TATTOO 2",
                            PersonId = 1,
                            Style = 2,
                            Technique = 1
                        },
                        new
                        {
                            Id = 3,
                            City = "Krakow",
                            Color = 1,
                            Date = new DateTime(2020, 6, 17, 21, 12, 39, 322, DateTimeKind.Local).AddTicks(3248),
                            Gender = 2,
                            ImgSrc = "sciezka TATTOO 3",
                            PersonId = 2,
                            Style = 3,
                            Technique = 2
                        });
                });

            modelBuilder.Entity("PortalApi.Entities.Article", b =>
                {
                    b.HasOne("PortalApi.Entities.ArticleSubcategory", "ArticleSubcategory")
                        .WithMany("Articles")
                        .HasForeignKey("ArticleSubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalApi.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalApi.Entities.ArticleSubcategory", b =>
                {
                    b.HasOne("PortalApi.Entities.ArticleCategory", "ArticleCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ArticleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalApi.Entities.AvailableDesign", b =>
                {
                    b.HasOne("PortalApi.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalApi.Entities.City", b =>
                {
                    b.HasOne("PortalApi.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalApi.Entities.ModelPhoto", b =>
                {
                    b.HasOne("PortalApi.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalApi.Entities.PhotographerPhoto", b =>
                {
                    b.HasOne("PortalApi.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalApi.Entities.Piercing", b =>
                {
                    b.HasOne("PortalApi.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalApi.Entities.Tattoo", b =>
                {
                    b.HasOne("PortalApi.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
